# Generated by Django 6.0.2 on 2026-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
