# Generated by Django 6.0.2 on 2026-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='turf_images/'),
        ),
    ]
