# Generated by Django 6.0.2 on 2026-04-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0002_booking_is_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turf",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
