# Generated by Django 6.0.2 on 2026-02-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_turf_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='image',
            new_name='turf_image',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='name',
            new_name='turf_name',
        ),
    ]
