# Generated by Django 6.0.2 on 2026-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0004_booking_owner_amount_booking_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf",
            name="sport_type",
            field=models.CharField(
                choices=[
                    ("cricket", "Cricket"),
                    ("football", "Football"),
                    ("badminton", "Badminton"),
                    ("basketball", "Basketball"),
                ],
                default="football",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
