# Generated by Django 6.0.2 on 2026-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0005_turf_sport_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="turf",
            name="sport_type",
        ),
        migrations.AddField(
            model_name="turf",
            name="sports",
            field=models.ManyToManyField(to="Booking.sport"),
        ),
    ]
