# Generated by Django 6.0.2 on 2026-03-05 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Booking",
            "0007_turf_closing_time_turf_created_at_turf_opening_time_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["turf", "date"], name="Booking_boo_turf_id_6067ee_idx"
            ),
        ),
    ]
