# Generated by Django 6.0.2 on 2026-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0009_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="turf",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="turf",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
