# Generated by Django 6.0.2 on 2026-03-12 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0011_alter_booking_status_alter_review_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="sport",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Booking.sport",
            ),
            preserve_default=False,
        ),
    ]
