# Generated by Django 6.0.2 on 2026-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Booking", "0012_booking_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration",
            field=models.IntegerField(default=1),
        ),
    ]
