# Generated by Django 6.1 on 2026-08-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_preset',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
